# Generated by Django 2.1.5 on 2022-02-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255)),
                ('resultado_1', models.CharField(max_length=255)),
                ('resultado_2', models.CharField(max_length=255)),
                ('resultado_3', models.CharField(max_length=255)),
                ('resultado_4', models.CharField(max_length=255)),
                ('resultado_5', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome_integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.Integrante')),
            ],
        ),
    ]
