# Generated by Django 2.1.5 on 2022-02-26 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255)),
                ('resultado_1', models.CharField(max_length=255)),
                ('resultado_2', models.CharField(blank=True, max_length=255)),
                ('resultado_3', models.CharField(blank=True, max_length=255)),
                ('resultado_4', models.CharField(blank=True, max_length=255)),
                ('resultado_5', models.CharField(blank=True, max_length=255)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.Integrante')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
