# Generated by Django 2.1.5 on 2022-02-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okr',
            old_name='nome_integrante',
            new_name='integrante',
        ),
    ]
