# Generated by Django 2.1.5 on 2022-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_auto_20220216_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='resultado_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='okr',
            name='resultado_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='okr',
            name='resultado_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='okr',
            name='resultado_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
