# Generated by Django 2.1.5 on 2022-02-26 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_auto_20220225_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
