# Generated by Django 2.1.5 on 2022-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_auto_20220216_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
