# Generated by Django 2.1.5 on 2022-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0004_auto_20220216_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okr',
            old_name='update_at',
            new_name='atualizado',
        ),
        migrations.RenameField(
            model_name='okr',
            old_name='created_at',
            new_name='criado',
        ),
    ]
